//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var data: data { .init(bundle: bundle) }
  var image: image { .init(bundle: bundle) }
  var entitlements: entitlements { .init() }
  var font: font { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func data(bundle: Foundation.Bundle) -> data {
    .init(bundle: bundle)
  }
  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func font(bundle: Foundation.Bundle) -> font {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.font.validate()
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "en"
  }

  /// This `_R.data` struct is generated, and contains static references to 1 datas.
  struct data {
    let bundle: Foundation.Bundle

    /// Data asset `img_style_placeholder`.
    var img_style_placeholder: RswiftResources.DataResource { .init(name: "img_style_placeholder", path: [], bundle: bundle, onDemandResourceTags: nil) }
  }

  /// This `_R.image` struct is generated, and contains static references to 62 images.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `Import Image`.
    var importImage: RswiftResources.ImageResource { .init(name: "Import Image", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `app_icon_1`.
    var app_icon_1: RswiftResources.ImageResource { .init(name: "app_icon_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `bg_choose_thumb`.
    var bg_choose_thumb: RswiftResources.ImageResource { .init(name: "bg_choose_thumb", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `bg_image_retouch`.
    var bg_image_retouch: RswiftResources.ImageResource { .init(name: "bg_image_retouch", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_pro`.
    var ic_pro: RswiftResources.ImageResource { .init(name: "ic_pro", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_sparkles`.
    var ic_sparkles: RswiftResources.ImageResource { .init(name: "ic_sparkles", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `ic_term`.
    var ic_term: RswiftResources.ImageResource { .init(name: "ic_term", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_app_anime`.
    var icon_app_anime: RswiftResources.ImageResource { .init(name: "icon_app_anime", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_app_email`.
    var icon_app_email: RswiftResources.ImageResource { .init(name: "icon_app_email", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_app_grammar`.
    var icon_app_grammar: RswiftResources.ImageResource { .init(name: "icon_app_grammar", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_app_logo`.
    var icon_app_logo: RswiftResources.ImageResource { .init(name: "icon_app_logo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_ds_tick_ac`.
    var icon_ds_tick_ac: RswiftResources.ImageResource { .init(name: "icon_ds_tick_ac", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_ds_tick_un`.
    var icon_ds_tick_un: RswiftResources.ImageResource { .init(name: "icon_ds_tick_un", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_empty`.
    var icon_empty: RswiftResources.ImageResource { .init(name: "icon_empty", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_gallery_ac`.
    var icon_gallery_ac: RswiftResources.ImageResource { .init(name: "icon_gallery_ac", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_gallery_un`.
    var icon_gallery_un: RswiftResources.ImageResource { .init(name: "icon_gallery_un", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_magic_gen`.
    var icon_magic_gen: RswiftResources.ImageResource { .init(name: "icon_magic_gen", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_magic_result`.
    var icon_magic_result: RswiftResources.ImageResource { .init(name: "icon_magic_result", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_premium`.
    var icon_premium: RswiftResources.ImageResource { .init(name: "icon_premium", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_pro_popup`.
    var icon_pro_popup: RswiftResources.ImageResource { .init(name: "icon_pro_popup", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_setting_about`.
    var icon_setting_about: RswiftResources.ImageResource { .init(name: "icon_setting_about", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_setting_contact`.
    var icon_setting_contact: RswiftResources.ImageResource { .init(name: "icon_setting_contact", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_setting_email`.
    var icon_setting_email: RswiftResources.ImageResource { .init(name: "icon_setting_email", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_setting_privacy`.
    var icon_setting_privacy: RswiftResources.ImageResource { .init(name: "icon_setting_privacy", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_setting_share`.
    var icon_setting_share: RswiftResources.ImageResource { .init(name: "icon_setting_share", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_setting_star`.
    var icon_setting_star: RswiftResources.ImageResource { .init(name: "icon_setting_star", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_setting_term`.
    var icon_setting_term: RswiftResources.ImageResource { .init(name: "icon_setting_term", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_show`.
    var icon_show: RswiftResources.ImageResource { .init(name: "icon_show", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_thumb_slider`.
    var icon_thumb_slider: RswiftResources.ImageResource { .init(name: "icon_thumb_slider", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_unknow`.
    var icon_unknow: RswiftResources.ImageResource { .init(name: "icon_unknow", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `icon_unlimit`.
    var icon_unlimit: RswiftResources.ImageResource { .init(name: "icon_unlimit", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `image_feature`.
    var image_feature: RswiftResources.ImageResource { .init(name: "image_feature", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `image_premium_modal`.
    var image_premium_modal: RswiftResources.ImageResource { .init(name: "image_premium_modal", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_back`.
    var img_back: RswiftResources.ImageResource { .init(name: "img_back", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_bg_ds`.
    var img_bg_ds: RswiftResources.ImageResource { .init(name: "img_bg_ds", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_camera`.
    var img_camera: RswiftResources.ImageResource { .init(name: "img_camera", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_circle_close`.
    var img_circle_close: RswiftResources.ImageResource { .init(name: "img_circle_close", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_close`.
    var img_close: RswiftResources.ImageResource { .init(name: "img_close", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_ds_bg`.
    var img_ds_bg: RswiftResources.ImageResource { .init(name: "img_ds_bg", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_ds_ticked`.
    var img_ds_ticked: RswiftResources.ImageResource { .init(name: "img_ds_ticked", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_ds_untick`.
    var img_ds_untick: RswiftResources.ImageResource { .init(name: "img_ds_untick", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_flower_star`.
    var img_flower_star: RswiftResources.ImageResource { .init(name: "img_flower_star", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_magic`.
    var img_magic: RswiftResources.ImageResource { .init(name: "img_magic", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_ob`.
    var img_ob: RswiftResources.ImageResource { .init(name: "img_ob", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_olive_close`.
    var img_olive_close: RswiftResources.ImageResource { .init(name: "img_olive_close", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_olive_tick`.
    var img_olive_tick: RswiftResources.ImageResource { .init(name: "img_olive_tick", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_photo`.
    var img_photo: RswiftResources.ImageResource { .init(name: "img_photo", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_placeholder`.
    var img_placeholder: RswiftResources.ImageResource { .init(name: "img_placeholder", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_premium_lock`.
    var img_premium_lock: RswiftResources.ImageResource { .init(name: "img_premium_lock", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_settings`.
    var img_settings: RswiftResources.ImageResource { .init(name: "img_settings", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `img_splash_screen`.
    var img_splash_screen: RswiftResources.ImageResource { .init(name: "img_splash_screen", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `onboarding_v1_1`.
    var onboarding_v1_1: RswiftResources.ImageResource { .init(name: "onboarding_v1_1", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `onboarding_v1_2`.
    var onboarding_v1_2: RswiftResources.ImageResource { .init(name: "onboarding_v1_2", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `onboarding_v1_3`.
    var onboarding_v1_3: RswiftResources.ImageResource { .init(name: "onboarding_v1_3", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `rating_stars`.
    var rating_stars: RswiftResources.ImageResource { .init(name: "rating_stars", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tab_create_selected`.
    var tab_create_selected: RswiftResources.ImageResource { .init(name: "tab_create_selected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tab_create_unselect`.
    var tab_create_unselect: RswiftResources.ImageResource { .init(name: "tab_create_unselect", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tab_history_selected`.
    var tab_history_selected: RswiftResources.ImageResource { .init(name: "tab_history_selected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tab_history_unselect`.
    var tab_history_unselect: RswiftResources.ImageResource { .init(name: "tab_history_unselect", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tab_setting_selected`.
    var tab_setting_selected: RswiftResources.ImageResource { .init(name: "tab_setting_selected", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `tab_setting_unselect`.
    var tab_setting_unselect: RswiftResources.ImageResource { .init(name: "tab_setting_unselect", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

    /// Image `view_blur`.
    var view_blur: RswiftResources.ImageResource { .init(name: "view_blur", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
  }

  /// This `_R.entitlements` struct is generated, and contains static references to 0 properties.
  struct entitlements {
    let comAppleSecurityAppSandbox: Bool = true
    let comAppleSecurityNetworkClient: Bool = true
  }

  /// This `_R.font` struct is generated, and contains static references to 12 fonts.
  struct font: Sequence {
    let bundle: Foundation.Bundle

    /// Font `Jost-Medium`.
    var jostMedium: RswiftResources.FontResource { .init(name: "Jost-Medium", bundle: bundle, filename: "Jost-Medium.ttf") }

    /// Font `Jost-Regular`.
    var jostRegular: RswiftResources.FontResource { .init(name: "Jost-Regular", bundle: bundle, filename: "Jost-Regular.ttf") }

    /// Font `Jost-SemiBold`.
    var jostSemiBold: RswiftResources.FontResource { .init(name: "Jost-SemiBold", bundle: bundle, filename: "Jost-SemiBold.ttf") }

    /// Font `Patriona`.
    var patriona: RswiftResources.FontResource { .init(name: "Patriona", bundle: bundle, filename: "Patriona.ttf") }

    /// Font `Roboto-Bold`.
    var robotoBold: RswiftResources.FontResource { .init(name: "Roboto-Bold", bundle: bundle, filename: "Roboto-Bold.ttf") }

    /// Font `Roboto-Medium`.
    var robotoMedium: RswiftResources.FontResource { .init(name: "Roboto-Medium", bundle: bundle, filename: "Roboto-Medium.ttf") }

    /// Font `Roboto-Regular`.
    var robotoRegular: RswiftResources.FontResource { .init(name: "Roboto-Regular", bundle: bundle, filename: "Roboto-Regular.ttf") }

    /// Font `SFProText-Bold`.
    var sfProTextBold: RswiftResources.FontResource { .init(name: "SFProText-Bold", bundle: bundle, filename: "SF-Pro-Text-Bold.ttf") }

    /// Font `SFProText-Heavy`.
    var sfProTextHeavy: RswiftResources.FontResource { .init(name: "SFProText-Heavy", bundle: bundle, filename: "SF-Pro-Text-Heavy.ttf") }

    /// Font `SFProText-Medium`.
    var sfProTextMedium: RswiftResources.FontResource { .init(name: "SFProText-Medium", bundle: bundle, filename: "SF-Pro-Text-Medium.ttf") }

    /// Font `SFProText-Regular`.
    var sfProTextRegular: RswiftResources.FontResource { .init(name: "SFProText-Regular", bundle: bundle, filename: "SF-Pro-Text-Regular.ttf") }

    /// Font `SFProText-Semibold`.
    var sfProTextSemibold: RswiftResources.FontResource { .init(name: "SFProText-Semibold", bundle: bundle, filename: "SF-Pro-Text-Semibold.ttf") }

    func makeIterator() -> IndexingIterator<[RswiftResources.FontResource]> {
      [jostMedium, jostRegular, jostSemiBold, patriona, robotoBold, robotoMedium, robotoRegular, sfProTextBold, sfProTextHeavy, sfProTextMedium, sfProTextRegular, sfProTextSemibold].makeIterator()
    }
    func validate() throws {
      for font in self {
        if !font.canBeLoaded() { throw RswiftResources.ValidationError("[R.swift] Font '\(font.name)' could not be loaded, is '\(font.filename)' added to the UIAppFonts array in this targets Info.plist?") }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 20 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `GoogleService-Info.plist`.
    var googleServiceInfoPlist: RswiftResources.FileResource { .init(name: "GoogleService-Info", pathExtension: "plist", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Jost-Medium.ttf`.
    var jostMediumTtf: RswiftResources.FileResource { .init(name: "Jost-Medium", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Jost-Regular.ttf`.
    var jostRegularTtf: RswiftResources.FileResource { .init(name: "Jost-Regular", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Jost-SemiBold.ttf`.
    var jostSemiBoldTtf: RswiftResources.FileResource { .init(name: "Jost-SemiBold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Patriona.ttf`.
    var patrionaTtf: RswiftResources.FileResource { .init(name: "Patriona", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Plist`.
    var plist: RswiftResources.FileResource { .init(name: "Plist", pathExtension: "", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `PrivacyInfo.xcprivacy`.
    var privacyInfoXcprivacy: RswiftResources.FileResource { .init(name: "PrivacyInfo", pathExtension: "xcprivacy", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Roboto-Bold.ttf`.
    var robotoBoldTtf: RswiftResources.FileResource { .init(name: "Roboto-Bold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Roboto-Medium.ttf`.
    var robotoMediumTtf: RswiftResources.FileResource { .init(name: "Roboto-Medium", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `Roboto-Regular.ttf`.
    var robotoRegularTtf: RswiftResources.FileResource { .init(name: "Roboto-Regular", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `SF-Pro-Text-Bold.ttf`.
    var sfProTextBoldTtf: RswiftResources.FileResource { .init(name: "SF-Pro-Text-Bold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `SF-Pro-Text-Heavy.ttf`.
    var sfProTextHeavyTtf: RswiftResources.FileResource { .init(name: "SF-Pro-Text-Heavy", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `SF-Pro-Text-Medium.ttf`.
    var sfProTextMediumTtf: RswiftResources.FileResource { .init(name: "SF-Pro-Text-Medium", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `SF-Pro-Text-Regular.ttf`.
    var sfProTextRegularTtf: RswiftResources.FileResource { .init(name: "SF-Pro-Text-Regular", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `SF-Pro-Text-Semibold.ttf`.
    var sfProTextSemiboldTtf: RswiftResources.FileResource { .init(name: "SF-Pro-Text-Semibold", pathExtension: "ttf", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `data_about.json`.
    var data_aboutJson: RswiftResources.FileResource { .init(name: "data_about", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `data_app.json`.
    var data_appJson: RswiftResources.FileResource { .init(name: "data_app", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `data_onboarding.json`.
    var data_onboardingJson: RswiftResources.FileResource { .init(name: "data_onboarding", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `example_book.json`.
    var example_bookJson: RswiftResources.FileResource { .init(name: "example_book", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }

    /// Resource file `generating_loading_anim.json`.
    var generating_loading_animJson: RswiftResources.FileResource { .init(name: "generating_loading_anim", pathExtension: "json", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var main: main { .init(bundle: bundle) }

    func main(bundle: Foundation.Bundle) -> main {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.main.validate()
    }


    /// Storyboard `Main`.
    struct main: RswiftResources.StoryboardReference {
      let bundle: Foundation.Bundle

      let name = "Main"
      func validate() throws {

      }
    }
  }
}